version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  build:
    commands:
      - echo Building, Testing and packaging the application...
      - mvn package -DskipTests
  post_build:
    commands:
      - echo Build, Testing and packaging completed.
artifacts:
  files:
    - target/*.jar
    - scripts/*.sh
    - appspec.yaml
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'